### ISSUE TITLE
Crash on otherwise correct profile when I click get stats for whole file in the upper left on spall web

### ISSUE THREAD

**Issue by creikey** [colrdavidson/spall#22]
Here is the stacktrace:
```
ntimeError: unreachable
    at runtime.bounds_check_error.handle_error-0 (00567362:0xd08e)
    at frame (00567362:0x3f253)
    at Object.value [as frame] (wasm_runtime.js:308:24)
    at doFrame (spall.js:682:29)
doFrame @ spall.js:684
```
Here is the file that failed it:
[rpgpt.zip](https://github.com/colrdavidson/spall/files/11269331/rpgpt.zip)

Let me know if you need anything else, such as source code. Thanks for making spall!

**Comment by colrdavidson** [comment]
Hmm. I'll double check with your data, but this smells of OOM to me. There are a few looming OOM issues that don't throw an error, because Odin does slice indexing with pointer-sized signed values. It's likely that it's trying to index with a "negative" number that's not actually negative, somewhere in rendering.

Working on getting this fixed on the compiler-side at some point.

**Comment by colrdavidson** [comment]
Nah with a trace that small, this is definitely not an OOM. There's a bug in my stat generation somewhere. I'll dig around and see if I can find it.
